version: "3.7"

services:
  node-red:
    container_name: "NodeRed"
    image: nodered/node-red:latest
    environment:
      - TZ=America/Sao_Paulo
      #- PGID=1000
      #- PUID=1000
    user: "root:root"
    ports:
      - "1880:1880"
    networks:
      - home-system-net
    volumes:
      - home-system-data:/data
  hass:
    container_name: "HomeAssistant"
    network_mode: host
    image: homeassistant/raspberrypi3-homeassistant:stable
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "8123:8123"
    volumes:
      - home-system-data:/config
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: "mqtt"
    restart: always
    network_mode: host
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - home-system-data:/mosquitto/data
      #- home-system-data:/mosquitto/config
      - home-system-data:/mosquitto/log
    environment:
      - TZ=America/Sao_Paulo
  
volumes:
  home-system-data:

networks:
  home-system-net:
